application: giftshowapt
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /assets
  static_dir: assets
- url: /img
  static_dir: img
- url: .*
  script: main.app


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

